import { Tariff } from '@/shared/api/types'

export const subscriptionPlans = [
  {
    name: Tariff.BASIC,
    price: 0,
    details: {
      nftTotalQuantity: 5,
      nftArtwork: 20,
      collectionsQuantity: 2,
      collectibleSBT: 'Bronze',
      commission: 8,
      organizationAddition: 0,
      customCollectionDesign: false,
      accountRating: true,
      nftPurchaseAbility: true,
      internalWalletCreation: true,
      prioritySupport: false,
      closedCommunity: false,
      personalManager: false,
      status: 'нет',
      tokenCreation: 0,
      referralConnection: 0,
    },
  },
  {
    name: Tariff.STANDARD,
    price: 19.99,
    details: {
      nftTotalQuantity: 20,
      nftArtwork: 250,
      collectionsQuantity: 10,
      collectibleSBT: 'Silver',
      commission: 6,
      organizationAddition: 1,
      customCollectionDesign: false,
      accountRating: true,
      nftPurchaseAbility: true,
      internalWalletCreation: true,
      prioritySupport: false,
      closedCommunity: false,
      personalManager: false,
      status: 'нет',
      tokenCreation: 1,
      referralConnection: 1,
    },
  },
  {
    name: Tariff.PREMIUM,
    price: 49.99,
    details: {
      nftTotalQuantity: 50,
      nftArtwork: 1000,
      collectionsQuantity: 25,
      collectibleSBT: 'Gold',
      commission: 5,
      organizationAddition: 2,
      customCollectionDesign: true,
      accountRating: true,
      nftPurchaseAbility: true,
      internalWalletCreation: true,
      prioritySupport: true,
      closedCommunity: true,
      personalManager: false,
      status: 'нет',
      tokenCreation: 2,
      referralConnection: 2,
    },
  },
  {
    name: Tariff.BLACK,
    price: 299.99,
    details: {
      nftTotalQuantity: 100,
      nftArtwork: 5000,
      collectionsQuantity: 50,
      collectibleSBT: 'Black',
      commission: 3,
      organizationAddition: 5,
      customCollectionDesign: true,
      accountRating: true,
      nftPurchaseAbility: true,
      internalWalletCreation: true,
      prioritySupport: true,
      closedCommunity: true,
      personalManager: true,
      status: 'Private',
      tokenCreation: 5,
      referralConnection: 12,
    },
  },
]
